/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ulbra.view;

/**
 *
 * @author s.lucas
 */
public class FPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FPrincipal
     */
    public FPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtHoras = new javax.swing.JTextField();
        lbHE = new javax.swing.JLabel();
        txtHE = new javax.swing.JTextField();
        btGerar = new javax.swing.JButton();
        lbClean = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lbHolerite = new javax.swing.JLabel();
        lbFuncionario = new javax.swing.JLabel();
        lbQuantH = new javax.swing.JLabel();
        lbQuantHE = new javax.swing.JLabel();
        lbSalarioB = new javax.swing.JLabel();
        lbVHE = new javax.swing.JLabel();
        lbINSS = new javax.swing.JLabel();
        lbSalF = new javax.swing.JLabel();
        lbIR = new javax.swing.JLabel();
        lbSalL = new javax.swing.JLabel();
        lbRSalarioB = new javax.swing.JLabel();
        lbVHER = new javax.swing.JLabel();
        lbSalFR = new javax.swing.JLabel();
        lbHorasR = new javax.swing.JLabel();
        lbHER = new javax.swing.JLabel();
        lbINSSR = new javax.swing.JLabel();
        lbNomeR = new javax.swing.JLabel();
        lbRIR = new javax.swing.JLabel();
        lbRSalL = new javax.swing.JLabel();
        lbTitulo = new javax.swing.JLabel();
        lbNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lbValorH = new javax.swing.JLabel();
        txtValorH = new javax.swing.JTextField();
        lbFilhos = new javax.swing.JLabel();
        txtFilhos = new javax.swing.JTextField();
        lbHoras = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbHE.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        lbHE.setText("Quant. horas extras");

        btGerar.setBackground(new java.awt.Color(31, 241, 38));
        btGerar.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        btGerar.setText("Gerar folha");
        btGerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGerarActionPerformed(evt);
            }
        });

        lbClean.setBackground(new java.awt.Color(219, 33, 33));
        lbClean.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        lbClean.setText("Limpar");
        lbClean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbCleanActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 0, 153));

        lbHolerite.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        lbHolerite.setText("Holerite - Maio/2023");

        lbFuncionario.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        lbFuncionario.setText("Funcionário: ");

        lbQuantH.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        lbQuantH.setText("Quant. horas:");

        lbQuantHE.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        lbQuantHE.setText("Quant. horas extras:");

        lbSalarioB.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        lbSalarioB.setText("Salário bruto:");

        lbVHE.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        lbVHE.setText("Valor horas extras:");

        lbINSS.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        lbINSS.setText("Desconto INSS:  R$");

        lbSalF.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        lbSalF.setText("Valor sal. família:  R$");

        lbIR.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        lbIR.setText("Desconto IR:  R$");

        lbSalL.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        lbSalL.setText("Salário liquido:  R$");

        lbRSalarioB.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        lbRSalarioB.setText("???");

        lbVHER.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        lbVHER.setText("???");

        lbSalFR.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        lbSalFR.setText("???");

        lbHorasR.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        lbHorasR.setText("???");

        lbHER.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        lbHER.setText("???");

        lbINSSR.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        lbINSSR.setText("???");

        lbNomeR.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        lbNomeR.setText("???");

        lbRIR.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        lbRIR.setText("???");

        lbRSalL.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        lbRSalL.setText("???");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lbQuantH)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbHorasR, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lbQuantHE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                                .addComponent(lbHER, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(lbVHE)
                                .addGap(18, 18, 18)
                                .addComponent(lbVHER, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(110, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(lbFuncionario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbNomeR, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lbRIR, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(lbINSS)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lbINSSR, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbHolerite)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lbSalarioB)
                                .addGap(18, 18, 18)
                                .addComponent(lbRSalarioB, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(lbIR)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lbSalL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbRSalL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(48, 48, 48))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lbSalF)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbSalFR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(33, 33, 33))))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lbHolerite)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbFuncionario)
                    .addComponent(lbNomeR))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbQuantH)
                    .addComponent(lbQuantHE)
                    .addComponent(lbHorasR)
                    .addComponent(lbHER))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbVHE)
                    .addComponent(lbVHER)
                    .addComponent(lbSalarioB)
                    .addComponent(lbRSalarioB))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbINSS)
                    .addComponent(lbINSSR)
                    .addComponent(lbSalF)
                    .addComponent(lbSalFR))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbIR)
                        .addComponent(lbSalL)
                        .addComponent(lbRSalL))
                    .addComponent(lbRIR))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        lbTitulo.setFont(new java.awt.Font("Cambria Math", 1, 20)); // NOI18N
        lbTitulo.setText("FOLHA DE PAGAMENTO");

        lbNome.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        lbNome.setText("Funcionário (nome)");

        lbValorH.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        lbValorH.setText("Valor hora");

        lbFilhos.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        lbFilhos.setText("Quant. filhos");

        lbHoras.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        lbHoras.setText("Quant. horas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(199, 199, 199)
                .addComponent(btGerar)
                .addGap(67, 67, 67)
                .addComponent(lbClean)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(44, 44, 44))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbNome)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbValorH)
                                    .addComponent(txtValorH, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(61, 61, 61)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbFilhos)
                                    .addComponent(txtFilhos, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbHE, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbHoras)
                                .addComponent(txtHoras, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtHE, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbTitulo)
                .addGap(258, 258, 258))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lbTitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNome)
                    .addComponent(lbHoras))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbValorH)
                    .addComponent(lbFilhos)
                    .addComponent(lbHE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtValorH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFilhos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btGerar)
                    .addComponent(lbClean))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btGerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGerarActionPerformed
        double sL, salB, salHE, salF, quantH, valorH, filhos,quantHE, iNSS, iR;

        lbNomeR.setText(txtNome.getText());
        lbHorasR.setText(txtHoras.getText());
        lbHER.setText(txtHE.getText());
        quantH = Double.parseDouble(txtHoras.getText());
        valorH = Double.parseDouble(txtValorH.getText());
        filhos = Double.parseDouble(txtFilhos.getText());
        quantHE = Double.parseDouble(txtHE.getText());

        salB = quantH * valorH;
        salHE = quantHE * (valorH * 1.5);
        salF = filhos * 15;

        lbRSalarioB.setText(String.valueOf(salB));
        lbVHER.setText(String.valueOf(salHE));
        lbSalFR.setText(String.valueOf(salF));

        //INSS
        if (salB <= 1320.00) {
            iNSS = salB * 0.075;
            lbINSSR.setText(String.valueOf(iNSS));
        } else if (salB > 1320.00 && salB <= 2571.29) {
            iNSS = salB * 0.09;
            lbINSSR.setText(String.valueOf(iNSS));
        } else if (salB > 2571.29 && salB <= 3856.94) {
            iNSS = salB * 0.12;
            lbINSSR.setText(String.valueOf(iNSS));
        } else {
            iNSS = salB * 0.14;
            lbINSSR.setText(String.valueOf(iNSS));
        }

        //IR
        if (salB < 1903.09) {
            iR = 0;
            lbRIR.setText(String.valueOf(iR));
        } else if (salB >= 1903.09 && salB <= 2826.65) {
            iR = salB * 0.075;
            lbRIR.setText(String.valueOf(iR));
        } else if (salB > 2826.65 && salB <= 3751.05) {
            iR = salB * 0.15;
            lbRIR.setText(String.valueOf(iR));
        } else if (salB > 3751.05 && salB <= 4663.68) {
            iR = salB * 0.225;
            lbRIR.setText(String.valueOf(iR));
        } else {
            iR = salB * 0.275;
            lbRIR.setText(String.valueOf(iR));
        }

        //Salário líquido
        sL = salB + salF + salHE - iNSS - iR;

        lbRSalL.setText(String.valueOf(sL));
    }//GEN-LAST:event_btGerarActionPerformed

    private void lbCleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbCleanActionPerformed
        txtNome.setText(null);
        txtHoras.setText(null);
        txtValorH.setText(null);
        txtFilhos.setText(null);
        txtHE.setText(null);
    }//GEN-LAST:event_lbCleanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btGerar;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton lbClean;
    private javax.swing.JLabel lbFilhos;
    private javax.swing.JLabel lbFuncionario;
    private javax.swing.JLabel lbHE;
    private javax.swing.JLabel lbHER;
    private javax.swing.JLabel lbHolerite;
    private javax.swing.JLabel lbHoras;
    private javax.swing.JLabel lbHorasR;
    private javax.swing.JLabel lbINSS;
    private javax.swing.JLabel lbINSSR;
    private javax.swing.JLabel lbIR;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbNomeR;
    private javax.swing.JLabel lbQuantH;
    private javax.swing.JLabel lbQuantHE;
    private javax.swing.JLabel lbRIR;
    private javax.swing.JLabel lbRSalL;
    private javax.swing.JLabel lbRSalarioB;
    private javax.swing.JLabel lbSalF;
    private javax.swing.JLabel lbSalFR;
    private javax.swing.JLabel lbSalL;
    private javax.swing.JLabel lbSalarioB;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JLabel lbVHE;
    private javax.swing.JLabel lbVHER;
    private javax.swing.JLabel lbValorH;
    private javax.swing.JTextField txtFilhos;
    private javax.swing.JTextField txtHE;
    private javax.swing.JTextField txtHoras;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtValorH;
    // End of variables declaration//GEN-END:variables
}
